import { Organization, Profile, Instance, KanbanStage, Queue, Tag, Contact, Chat, Message, QuickReply } from '../types';

export const mockOrganization: Organization = {
  id: 'a0000000-0000-0000-0000-000000000001',
  name: 'Nexus Digital Tech',
  slug: 'nexus-digital',
  plan: 'pro',
  max_instances: 5,
  max_agents: 10,
  status: 'active',
};

export const mockProfile: Profile = {
  id: 'p0000000-0000-0000-0000-000000000001',
  organization_id: mockOrganization.id,
  full_name: 'Carlos Oliveira (Você)',
  email: 'carlos@nexusdigital.com',
  role: 'admin',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  is_online: true,
};

export const mockQueues: Queue[] = [
  { id: 'q1', organization_id: mockOrganization.id, name: 'Comercial & Vendas', color: '#3B82F6' },
  { id: 'q2', organization_id: mockOrganization.id, name: 'Suporte Técnico', color: '#10B981' },
  { id: 'q3', organization_id: mockOrganization.id, name: 'Financeiro', color: '#F59E0B' },
];

export const mockTags: Tag[] = [
  { id: 't1', organization_id: mockOrganization.id, name: 'Quente 🔥', color: '#EF4444' },
  { id: 't2', organization_id: mockOrganization.id, name: 'Cliente VIP ⭐', color: '#8B5CF6' },
  { id: 't3', organization_id: mockOrganization.id, name: 'Aguardando PIX 💰', color: '#10B981' },
  { id: 't4', organization_id: mockOrganization.id, name: 'Retornar Tarde ⏰', color: '#F97316' },
];

export const mockKanbanStages: KanbanStage[] = [
  { id: 's1', organization_id: mockOrganization.id, name: 'Novo Lead', color: '#3B82F6', order_index: 1 },
  { id: 's2', organization_id: mockOrganization.id, name: 'Primeiro Contato', color: '#8B5CF6', order_index: 2 },
  { id: 's3', organization_id: mockOrganization.id, name: 'Proposta Enviada', color: '#F59E0B', order_index: 3 },
  { id: 's4', organization_id: mockOrganization.id, name: 'Em Negociação', color: '#EC4899', order_index: 4 },
  { id: 's5', organization_id: mockOrganization.id, name: 'Fechado (Ganho) 🎉', color: '#10B981', order_index: 5 },
];

export const mockInstances: Instance[] = [
  {
    id: '7e57f972-7699-4f52-b232-a54650890ee7',
    organization_id: mockOrganization.id,
    name: 'WhatsApp Contabo (Oficial)',
    instance_name: 'org_a0000000_1790214378377',
    status: 'qrcode',
    phone_number: null,
    profile_picture_url: null,
    created_at: new Date().toISOString(),
  },
];

export const mockContacts: Contact[] = [
  {
    id: 'c1',
    organization_id: mockOrganization.id,
    remote_jid: '5511999991111@s.whatsapp.net',
    phone: '5511999991111',
    name: 'Mariana Ribeiro',
    push_name: 'Mariana',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    kanban_stage_id: 's3',
    queue_id: 'q1',
    deal_value: 3850.00,
    tags: [mockTags[0], mockTags[1]],
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'c2',
    organization_id: mockOrganization.id,
    remote_jid: '5521988882222@s.whatsapp.net',
    phone: '5521988882222',
    name: 'Lucas Mendes - Agência Alfa',
    push_name: 'Lucas Mendes',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    kanban_stage_id: 's4',
    queue_id: 'q1',
    deal_value: 7500.00,
    tags: [mockTags[2]],
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: 'c3',
    organization_id: mockOrganization.id,
    remote_jid: '5531977773333@s.whatsapp.net',
    phone: '5531977773333',
    name: 'Dra. Fernanda Castro',
    push_name: 'Fernanda Castro',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    kanban_stage_id: 's1',
    queue_id: 'q2',
    deal_value: 1200.00,
    tags: [mockTags[3]],
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: 'c4',
    organization_id: mockOrganization.id,
    remote_jid: '5541966664444@s.whatsapp.net',
    phone: '5541966664444',
    name: 'Roberto Silveira',
    push_name: 'Roberto',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    kanban_stage_id: 's5',
    queue_id: 'q1',
    deal_value: 12400.00,
    tags: [mockTags[1]],
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
];

export const mockChats: Chat[] = [
  {
    id: 'chat-1',
    organization_id: mockOrganization.id,
    instance_id: 'inst-1',
    contact_id: 'c1',
    status: 'in_progress',
    unread_count: 2,
    last_message_text: 'Acabei de escutar o áudio! Tem como me mandar o contrato em PDF?',
    last_message_at: new Date(Date.now() - 60000 * 8).toISOString(),
    contact: mockContacts[0],
    instance: mockInstances[0],
  },
  {
    id: 'chat-2',
    organization_id: mockOrganization.id,
    instance_id: 'inst-1',
    contact_id: 'c2',
    status: 'in_progress',
    unread_count: 0,
    last_message_text: 'Perfeito Carlos, já autorizei o financeiro para fazer o PIX.',
    last_message_at: new Date(Date.now() - 60000 * 45).toISOString(),
    contact: mockContacts[1],
    instance: mockInstances[0],
  },
  {
    id: 'chat-3',
    organization_id: mockOrganization.id,
    instance_id: 'inst-1',
    contact_id: 'c3',
    status: 'open',
    unread_count: 1,
    last_message_text: 'Bom dia! Gostaria de saber mais informações sobre os planos.',
    last_message_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    contact: mockContacts[2],
    instance: mockInstances[0],
  },
  {
    id: 'chat-4',
    organization_id: mockOrganization.id,
    instance_id: 'inst-1',
    contact_id: 'c4',
    status: 'resolved',
    unread_count: 0,
    last_message_text: 'Obrigado pelo suporte rápido, já estou usando o sistema!',
    last_message_at: new Date(Date.now() - 3600000 * 18).toISOString(),
    contact: mockContacts[3],
    instance: mockInstances[0],
  },
];

export const mockMessages: Record<string, Message[]> = {
  'chat-1': [
    {
      id: 'm1',
      organization_id: mockOrganization.id,
      chat_id: 'chat-1',
      direction: 'inbound',
      sender_type: 'contact',
      type: 'text',
      content: 'Olá Carlos! Vi a demonstração do CRM e fiquei muito interessada na automação do WhatsApp.',
      status: 'read',
      created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    },
    {
      id: 'm2',
      organization_id: mockOrganization.id,
      chat_id: 'chat-1',
      direction: 'outbound',
      sender_type: 'agent',
      type: 'text',
      content: 'Olá Mariana, seja muito bem-vinda! Com certeza, a nossa integração com a Evolution Go é perfeita para reduzir o custo de servidor e atender com múltiplos agentes.',
      status: 'read',
      created_at: new Date(Date.now() - 3600000 * 1.8).toISOString(),
    },
    {
      id: 'm3',
      organization_id: mockOrganization.id,
      chat_id: 'chat-1',
      direction: 'outbound',
      sender_type: 'agent',
      type: 'internal_note',
      content: '📌 Lead com alto potencial de fechamento no plano anual. Oferecer 15% de desconto no PIX se fechar hoje.',
      is_internal_note: true,
      status: 'sent',
      created_at: new Date(Date.now() - 3600000 * 1.5).toISOString(),
    },
    {
      id: 'm4',
      organization_id: mockOrganization.id,
      chat_id: 'chat-1',
      direction: 'outbound',
      sender_type: 'agent',
      type: 'audio',
      content: '🎵 Mensagem de voz',
      media_url: 'https://actions.google.com/sounds/v1/water/waves_crashing_against_cliff.ogg',
      media_duration: 24,
      status: 'read',
      created_at: new Date(Date.now() - 3600000 * 1.2).toISOString(),
    },
    {
      id: 'm5',
      organization_id: mockOrganization.id,
      chat_id: 'chat-1',
      direction: 'inbound',
      sender_type: 'contact',
      type: 'text',
      content: 'Acabei de escutar o áudio! Ficou muito claro. Tem como me mandar a proposta em PDF para eu assinar?',
      status: 'delivered',
      created_at: new Date(Date.now() - 60000 * 8).toISOString(),
    },
  ],
};

export const mockQuickReplies: QuickReply[] = [
  {
    id: 'qr-1',
    organization_id: mockOrganization.id,
    shortcut: '/ola',
    title: 'Boas-vindas Padrão',
    content: 'Olá! Tudo bem? Me chamo Carlos da Nexus Tech. Como posso te ajudar hoje?',
  },
  {
    id: 'qr-2',
    organization_id: mockOrganization.id,
    shortcut: '/pix',
    title: 'Chave PIX e Pagamento',
    content: 'Nossa chave PIX CNPJ é: 12.345.678/0001-90 (Banco Inter). Assim que realizar o pagamento, basta enviar o comprovante por aqui para liberarmos seu acesso!',
  },
  {
    id: 'qr-3',
    organization_id: mockOrganization.id,
    shortcut: '/horario',
    title: 'Horário de Atendimento',
    content: 'Nosso time atende de Segunda a Sexta, das 08:30 às 18:30. Mensagens fora desse horário serão respondidas no próximo dia útil!',
  },
  {
    id: 'qr-4',
    organization_id: mockOrganization.id,
    shortcut: '/reuniao',
    title: 'Agendamento de Demonstração',
    content: 'Pode escolher o melhor horário para conversarmos por vídeo neste link da nossa agenda: https://cal.com/nexus/demo',
  },
];
